# Generated by Django 3.2.12 on 2022-02-13 18:55

import clusters.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True)),
                ("ts_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(default=clusters.models.default_config)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
