# Generated by Django 3.2.12 on 2022-02-13 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ts_created", models.DateTimeField(auto_now_add=True)),
                ("ts_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("topics", models.CharField(max_length=300)),
                (
                    "serialization_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("xml", "XML")],
                        default="json",
                        max_length=100,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, null=True)),
                (
                    "ts_expire",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "batch_size",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "batch_max_interval",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
